// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"form-container sign-up-container\"><form hx-post=\"/signup\" hx-target=\"#message\" hx-swap=\"innerHTML\"><h1>Create Account</h1><input type=\"text\" name=\"name\" placeholder=\"Name\" required> <input type=\"email\" name=\"email\" placeholder=\"Email\" required> <input type=\"password\" name=\"password\" placeholder=\"Password\" required><div class=\"radio-group\"><label><input type=\"radio\" name=\"userType\" value=\"user\" required> User</label> <label><input type=\"radio\" name=\"userType\" value=\"propietary\" required> Propietary</label> <label><input type=\"radio\" name=\"userType\" value=\"propietary\" required> Administrator</label></div><button type=\"submit\">Sign Up</button></form></div><div class=\"form-container sign-in-container\"><form hx-post=\"/login\" hx-target=\"#message\" hx-swap=\"innerHTML\"><h1>Sign in</h1><input type=\"email\" name=\"email\" placeholder=\"Email\" required> <input type=\"password\" name=\"password\" placeholder=\"Password\" required> <button type=\"submit\">Sign In</button></form></div><div class=\"overlay-container\"><div class=\"overlay\"><div class=\"overlay-panel overlay-left\"><h1>Welcome Back!</h1><p>To keep connected with us please login with your personal info</p><button class=\"ghost\" id=\"signIn\">Sign In</button></div><div class=\"overlay-panel overlay-right\"><h1>Hello, Friend!</h1><p>Enter your personal details and start journey with us</p><button class=\"ghost\" id=\"signUp\">Sign Up</button></div></div></div></div><div id=\"message\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
